[package]
name = "jira_ish_cli"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sqlite = "0.27.0"
dotenv = "0.15.0"
regex = "1.5"
crypto-hash = "0.3.4"
termion = "1.5.6"
